// AI 응답을 PDF로 다운로드 (Tori 17989643 후속 — Roy 직접 요청 2026-04-28)
//
// 사용자가 "PDF로 다운로드" 요청 시 AI가 답변(번역/요약/재구성 등)을
// 마쳤을 때 자동으로 그 답변 본문을 PDF로 렌더링·다운로드.
//
// 구조 — export-meeting-pdf.ts의 다크모드 cascade 차단 패턴 재활용.

import { sanitizeFilename, formatDateForFilename } from './sanitize-filename';

export interface ResponseExportData {
  title: string;          // 사용자 요청에서 유도된 제목 (예: "Vibe+Coding 한국어 번역")
  body: string;           // AI 응답 본문 (마크다운 또는 plain text)
  sourceFiles?: string[]; // 출처 (예: ["Vibe+Coding+vs+Agentic+Coding+Fundamentals.pdf"])
  createdAt?: number;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// 간단 마크다운 → HTML (heading / list / paragraph만 처리, 다른 건 plain)
function simpleMarkdownToHtml(md: string): string {
  const lines = md.split('\n');
  const out: string[] = [];
  let inList = false;
  let inOl   = false;

  const flushList = () => {
    if (inList) { out.push('</ul>'); inList = false; }
    if (inOl)   { out.push('</ol>'); inOl = false; }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();

    // Heading
    const h = line.match(/^(#{1,6})\s+(.+)$/);
    if (h) {
      flushList();
      const lvl = Math.min(h[1].length, 6);
      out.push(`<h${lvl} style="margin:14pt 0 6pt 0;font-weight:600;">${escapeHtml(h[2])}</h${lvl}>`);
      continue;
    }

    // Bullet
    const bul = line.match(/^[-*+]\s+(.+)$/);
    if (bul) {
      if (!inList) { flushList(); out.push('<ul style="padding-left:18pt;margin:4pt 0;">'); inList = true; }
      out.push(`<li style="margin:2pt 0;">${escapeHtml(bul[1])}</li>`);
      continue;
    }

    // Numbered
    const num = line.match(/^\d+[.)]\s+(.+)$/);
    if (num) {
      if (!inOl) { flushList(); out.push('<ol style="padding-left:18pt;margin:4pt 0;">'); inOl = true; }
      out.push(`<li style="margin:2pt 0;">${escapeHtml(num[1])}</li>`);
      continue;
    }

    flushList();

    if (!line) {
      out.push('<div style="height:6pt;"></div>');
      continue;
    }

    // Plain paragraph — strip [source: ...] inline markers from final output
    const cleaned = line.replace(/\[source:[^\]]*\]/g, '').trim();
    if (cleaned) {
      out.push(`<p style="margin:4pt 0;line-height:1.7;">${escapeHtml(cleaned)}</p>`);
    }
  }
  flushList();
  return out.join('\n');
}

function fmtDate(ts: number, lang: 'ko' | 'en'): string {
  const d = new Date(ts);
  if (lang === 'ko') {
    const days = ['일', '월', '화', '수', '목', '금', '토'];
    return `${d.getFullYear()}년 ${d.getMonth() + 1}월 ${d.getDate()}일 (${days[d.getDay()]})`;
  }
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' });
}

function renderHTML(data: ResponseExportData, lang: 'ko' | 'en'): HTMLElement {
  const labels = lang === 'ko'
    ? { generated: 'Blend로 생성됨', sources: '출처' }
    : { generated: 'Generated by Blend', sources: 'Sources' };

  const dateStr = fmtDate(data.createdAt ?? Date.now(), lang);
  const bodyHtml = simpleMarkdownToHtml(data.body);
  const sourcesHtml = data.sourceFiles && data.sourceFiles.length > 0
    ? `
        <div class="d1-meta" style="margin-top:18pt;padding-top:8pt;border-top:1px dashed #d4d0c8;font-size:10pt;color:#6b6862;">
          <strong>${labels.sources}:</strong> ${data.sourceFiles.map(escapeHtml).join(' · ')}
        </div>`
    : '';

  const div = document.createElement('div');
  // Off-screen + dark-mode cascade 차단 (export-meeting-pdf 패턴 재활용)
  div.style.cssText = [
    'position:absolute',
    'left:-99999px',
    'top:0',
    'width:180mm',
    'background:#ffffff',
    'color:#0a0a0a',
    'color-scheme:light only',
    'forced-color-adjust:none',
    'isolation:isolate',
    'box-sizing:content-box',
  ].join(';');

  div.innerHTML = `
    <style>
      .d1-response-export-doc, .d1-response-export-doc * {
        color: #0a0a0a !important;
        background-color: transparent !important;
      }
      .d1-response-export-doc { background: #ffffff !important; }
      .d1-response-export-doc .d1-meta { color: #6b6862 !important; }
      .d1-response-export-doc .d1-foot { color: #a8a49b !important; }
      .d1-response-export-doc hr { border-top-color: #d4d0c8 !important; }
    </style>
    <div class="d1-response-export-doc" style="
      font-family: 'Pretendard Variable', Pretendard, -apple-system, sans-serif;
      color: #0a0a0a; background: #ffffff; padding: 0;
      width: 180mm; line-height: 1.6;
    ">
      <h1 style="font-size:20pt;margin:0 0 8pt 0;font-weight:600;letter-spacing:-0.02em;">
        ${escapeHtml(data.title || (lang === 'ko' ? 'Blend 답변' : 'Blend Response'))}
      </h1>
      <div class="d1-meta" style="color:#6b6862;font-size:10pt;line-height:1.5;">
        <div>${dateStr}</div>
      </div>
      <hr style="border:none;border-top:1px solid #d4d0c8;margin:12pt 0;" />

      <div style="line-height:1.7;font-size:11pt;">
        ${bodyHtml}
      </div>

      ${sourcesHtml}

      <div class="d1-foot" style="margin-top:24pt;padding-top:8pt;border-top:1px solid #e6e2dc;font-size:9pt;color:#a8a49b;text-align:center;font-style:italic;">
        ${labels.generated} · ${dateStr}
      </div>
    </div>
  `;
  return div;
}

export async function exportResponseAsPDF(
  data: ResponseExportData,
  lang: 'ko' | 'en'
): Promise<void> {
  const html2pdfModule = (await import('html2pdf.js')).default as (...args: unknown[]) => {
    set: (opts: object) => { from: (el: HTMLElement) => { save: () => Promise<void> } };
  };

  const element = renderHTML(data, lang);
  document.body.appendChild(element);

  // 폰트 로딩 대기 (Pretendard async race 방지)
  try { await document.fonts.ready; } catch { /* ignore */ }
  await new Promise((r) => setTimeout(r, 200));

  const measuredHeight = Math.max(element.scrollHeight, element.offsetHeight, 1);
  const measuredWidth  = Math.max(element.scrollWidth,  element.offsetWidth,  1);

  const filename = sanitizeFilename(
    `${data.title || 'blend-response'}_${formatDateForFilename(data.createdAt ?? Date.now())}.pdf`
  );

  const opt = {
    margin: [15, 15, 15, 15],
    filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      width:        measuredWidth,
      height:       measuredHeight,
      windowWidth:  measuredWidth,
      windowHeight: measuredHeight,
      logging: false,
    },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] as const },
  };

  try {
    await html2pdfModule().set(opt).from(element).save();
  } catch (e) {
    const err = e as Error;
    const wrapped = new Error(err.message || 'Response PDF export failed') as Error & { code?: string };
    wrapped.code = 'PDF_EXPORT_FAILED';
    throw wrapped;
  } finally {
    if (element.parentNode) element.parentNode.removeChild(element);
  }
}

/**
 * 사용자 메시지에 "PDF 다운로드" 의도가 있는지 검사.
 * 다운로드 의도 매칭되면 응답 완료 후 자동 PDF export.
 */
export function detectPdfDownloadIntent(message: string): boolean {
  if (!message) return false;
  const low = message.toLowerCase();
  // 한국어
  if (/pdf\s*(로|으로)?\s*(다운로드|받|저장|내려)/i.test(message)) return true;
  if (/(다운로드|저장).{0,8}pdf/i.test(message)) return true;
  // 영어
  if (/download.{0,12}(as|to|in)?\s*pdf/i.test(low)) return true;
  if (/(export|save).{0,12}(as|to|in)?\s*pdf/i.test(low)) return true;
  if (/pdf.{0,10}(download|export|file)/i.test(low)) return true;
  return false;
}
