// Meeting PDF 출력 — window.print → OS-level 텍스트 PDF
// (Tori 16384344 + Roy 2026-04-28 v3 결정)
//
// 이전: html2pdf.js + html2canvas — 빈 페이지 / 이미지 PDF / 다크모드 cascade
// 같은 회귀 다발. 어제(2026-04-27) v2에서 width:180mm + fonts.ready + measured
// dimensions로 패치했지만 일부 환경에서 여전히 빈 페이지.
//
// v3: window.open 새 창에 깔끔한 HTML 렌더 → 자동 print 다이얼로그.
// 사용자가 "PDF로 저장" 선택. 텍스트 기반 PDF, 한글 글리프 안전, 다크모드
// 무관. 회의 분석 PDF + AI 응답 PDF 양쪽 동일 패턴.

import { sanitizeFilename, formatDateForFilename } from './sanitize-filename';
import { printHtmlAsPDF } from './print-as-pdf';

type MeetingExportData = {
  id: string;
  title: string;
  createdAt: number;
  duration?: string;
  participants?: number;
  summary: string[];
  actionItems: { owner?: string; task: string; dueDate?: string; done?: boolean }[];
  decisions: string[];
  topics: string[];
  fullSummary: string;
  transcript?: { speaker?: string; text: string }[];
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function fmtDateKo(ts: number): string {
  const d = new Date(ts);
  const days = ['일','월','화','수','목','금','토'];
  return `${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일 (${days[d.getDay()]})`;
}

function fmtDateEn(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' });
}

function buildMeetingBody(meeting: MeetingExportData, lang: 'ko' | 'en'): string {
  const isKo = lang === 'ko';
  const labels = {
    summary:    isKo ? '요약' : 'Summary',
    actions:    isKo ? '실행 항목' : 'Action Items',
    decisions:  isKo ? '결정사항' : 'Decisions',
    topics:     isKo ? '토픽' : 'Topics',
    full:       isKo ? '전체 요약' : 'Full Summary',
    transcript: isKo ? '대화 기록' : 'Transcript',
    duration:   isKo ? '분석 시간' : 'Duration',
    participants: isKo ? '참석자' : 'Participants',
    suffix:     isKo ? '명' : '',
    generated:  isKo ? 'Blend로 생성됨' : 'Generated by Blend',
  };
  const dateStr = isKo ? fmtDateKo(meeting.createdAt) : fmtDateEn(meeting.createdAt);

  const summaryBlock = meeting.summary.length
    ? `<h2>${labels.summary}</h2><ul>${meeting.summary.map(s => `<li>${escapeHtml(s)}</li>`).join('')}</ul>`
    : '';

  const actionBlock = meeting.actionItems.length
    ? `<h2>${labels.actions}</h2><ul style="list-style:none;padding-left:0;">${meeting.actionItems.map(item => `
        <li style="margin:4pt 0;">
          ${item.done ? '☑' : '☐'}
          ${item.owner ? `<strong>[${escapeHtml(item.owner)}]</strong>` : ''}
          ${escapeHtml(item.task)}
          ${item.dueDate ? `<span class="meta"> · ${escapeHtml(item.dueDate)}</span>` : ''}
        </li>`).join('')}</ul>`
    : '';

  const decisionsBlock = meeting.decisions.length
    ? `<h2>${labels.decisions}</h2><ul>${meeting.decisions.map(d => `<li>${escapeHtml(d)}</li>`).join('')}</ul>`
    : '';

  const topicsBlock = meeting.topics.length
    ? `<h2>${labels.topics}</h2><p class="meta">${meeting.topics.map(escapeHtml).join(' · ')}</p>`
    : '';

  const fullBlock = meeting.fullSummary
    ? `<h2>${labels.full}</h2><p style="white-space:pre-wrap;">${escapeHtml(meeting.fullSummary)}</p>`
    : '';

  const transcriptBlock = meeting.transcript && meeting.transcript.length
    ? `<h2 style="page-break-before:always;">${labels.transcript}</h2>
       <div>${meeting.transcript.map((seg) => `
         <div style="margin:8pt 0;page-break-inside:avoid;">
           ${seg.speaker ? `<div style="font-size:11px;font-weight:600;color:#a04000;text-transform:uppercase;letter-spacing:0.04em;margin-bottom:2pt;">${escapeHtml(seg.speaker)}</div>` : ''}
           <p style="margin:0;white-space:pre-wrap;">${escapeHtml(seg.text)}</p>
         </div>
       `).join('')}</div>`
    : '';

  return `
    <h1>${escapeHtml(meeting.title || (isKo ? '회의록' : 'Meeting'))}</h1>
    <div class="meta">
      <div>${dateStr}</div>
      ${meeting.duration ? `<div>${labels.duration}: ${escapeHtml(meeting.duration)}</div>` : ''}
      ${meeting.participants ? `<div>${labels.participants}: ${meeting.participants}${labels.suffix}</div>` : ''}
    </div>
    <hr>
    ${summaryBlock}
    ${actionBlock}
    ${decisionsBlock}
    ${topicsBlock}
    ${fullBlock}
    ${transcriptBlock}
    <div class="footer">${labels.generated} · ${dateStr}</div>
  `;
}

export async function exportMeetingPDF(meeting: MeetingExportData, lang: 'ko' | 'en'): Promise<void> {
  // sanitize/formatDate는 새 파일명 힌트용으로만 사용 — 실제 파일명은
  // 사용자가 print 다이얼로그에서 결정. title을 그 힌트에 반영.
  const baseFilename = sanitizeFilename(
    `${meeting.title || 'meeting'}_${formatDateForFilename(meeting.createdAt)}`
  );
  const titleHint = baseFilename.replace(/_/g, ' ').slice(0, 60);

  try {
    printHtmlAsPDF({
      title: titleHint,
      bodyHtml: buildMeetingBody(meeting, lang),
      lang,
    });
  } catch (e) {
    const err = e as Error & { code?: string };
    const wrapped = new Error(err.message || 'PDF export failed') as Error & { code?: string };
    wrapped.code = err.code === 'POPUP_BLOCKED' ? 'POPUP_BLOCKED' : 'PDF_EXPORT_FAILED';
    throw wrapped;
  }
}
