// AI 응답을 PDF로 다운로드 (Tori 17989643 후속 — Roy 직접 요청 2026-04-28)
//
// 사용자가 "PDF로 다운로드" 요청 시 AI가 답변(번역/요약/재구성 등)을
// 마쳤을 때 자동으로 그 답변 본문을 PDF로 렌더링·다운로드.
//
// 2026-04-28 v2 — html2pdf.js → window.print 전환 (printHtmlAsPDF):
//   html2pdf+html2canvas 조합이 빈 페이지 / 이미지 PDF / 한글 글리프 누락 등
//   문제 다발. 새 창 + window.print() 방식으로 OS-level 텍스트 PDF 생성.
//   사용자는 인쇄 다이얼로그에서 "PDF로 저장" 선택. 트레이드오프: 1 클릭 추가.

import { printHtmlAsPDF } from './print-as-pdf';

export interface ResponseExportData {
  title: string;          // 사용자 요청에서 유도된 제목 (예: "Vibe+Coding 한국어 번역")
  body: string;           // AI 응답 본문 (마크다운 또는 plain text)
  sourceFiles?: string[]; // 출처 (예: ["Vibe+Coding+vs+Agentic+Coding+Fundamentals.pdf"])
  createdAt?: number;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// 간단 마크다운 → HTML
//   - heading (#~######), bullet/numbered list, paragraph
//   - **bold**, *italic*, `code`, code block (```)
//   - [source: ...] 인라인 마커 제거 (sourceFiles로 한 곳에 모음)
function simpleMarkdownToHtml(md: string): string {
  const lines = md.split('\n');
  const out: string[] = [];
  let inList = false;
  let inOl   = false;
  let inCode = false;
  let codeBuf: string[] = [];

  const flushList = () => {
    if (inList) { out.push('</ul>'); inList = false; }
    if (inOl)   { out.push('</ol>'); inOl = false; }
  };

  // inline format converter (bold/italic/code) — escape 후 적용
  const applyInline = (s: string): string => {
    let h = escapeHtml(s);
    h = h.replace(/`([^`]+)`/g, '<code>$1</code>');
    h = h.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
    h = h.replace(/\*([^*]+)\*/g, '<em>$1</em>');
    return h;
  };

  for (const raw of lines) {
    const line = raw.trimEnd();

    // 코드 블록 (```)
    if (line.startsWith('```')) {
      if (inCode) {
        out.push(`<pre><code>${escapeHtml(codeBuf.join('\n'))}</code></pre>`);
        codeBuf = [];
        inCode = false;
      } else {
        flushList();
        inCode = true;
      }
      continue;
    }
    if (inCode) {
      codeBuf.push(raw);
      continue;
    }

    // Heading
    const h = line.match(/^(#{1,6})\s+(.+)$/);
    if (h) {
      flushList();
      const lvl = Math.min(h[1].length, 6);
      out.push(`<h${lvl}>${applyInline(h[2])}</h${lvl}>`);
      continue;
    }

    // Bullet
    const bul = line.match(/^[-*+]\s+(.+)$/);
    if (bul) {
      if (!inList) { flushList(); out.push('<ul>'); inList = true; }
      out.push(`<li>${applyInline(bul[1])}</li>`);
      continue;
    }

    // Numbered
    const num = line.match(/^\d+[.)]\s+(.+)$/);
    if (num) {
      if (!inOl) { flushList(); out.push('<ol>'); inOl = true; }
      out.push(`<li>${applyInline(num[1])}</li>`);
      continue;
    }

    flushList();

    if (!line) {
      out.push('');
      continue;
    }

    // [source: ...] 인라인 마커 제거 후 paragraph
    const cleaned = line.replace(/\[source:[^\]]*\]/g, '').trim();
    if (cleaned) {
      out.push(`<p>${applyInline(cleaned)}</p>`);
    }
  }
  flushList();
  if (inCode && codeBuf.length > 0) {
    out.push(`<pre><code>${escapeHtml(codeBuf.join('\n'))}</code></pre>`);
  }
  return out.join('\n');
}

function fmtDate(ts: number, lang: 'ko' | 'en'): string {
  const d = new Date(ts);
  if (lang === 'ko') {
    const days = ['일', '월', '화', '수', '목', '금', '토'];
    return `${d.getFullYear()}년 ${d.getMonth() + 1}월 ${d.getDate()}일 (${days[d.getDay()]})`;
  }
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' });
}

export async function exportResponseAsPDF(
  data: ResponseExportData,
  lang: 'ko' | 'en'
): Promise<void> {
  const labels = lang === 'ko'
    ? { generated: 'Blend로 생성됨', sources: '출처' }
    : { generated: 'Generated by Blend', sources: 'Sources' };

  const dateStr = fmtDate(data.createdAt ?? Date.now(), lang);
  const bodyHtml = simpleMarkdownToHtml(data.body);
  const sourcesHtml = data.sourceFiles && data.sourceFiles.length > 0
    ? `<div class="source"><strong>${labels.sources}:</strong> ${data.sourceFiles.map(escapeHtml).join(' · ')}</div>`
    : '';

  const titleSafe = data.title || (lang === 'ko' ? 'Blend 답변' : 'Blend Response');

  const fullBody = `
    <h1>${escapeHtml(titleSafe)}</h1>
    <div class="meta">${dateStr}</div>
    <hr>
    ${bodyHtml}
    ${sourcesHtml}
    <div class="footer">${labels.generated} · ${dateStr}</div>
  `;

  printHtmlAsPDF({
    title: titleSafe,
    bodyHtml: fullBody,
    lang,
  });
}

/**
 * 사용자 메시지에 "PDF 다운로드" 의도가 있는지 검사.
 * 다운로드 의도 매칭되면 응답 완료 후 자동 PDF export.
 */
export function detectPdfDownloadIntent(message: string): boolean {
  if (!message) return false;
  const low = message.toLowerCase();
  // 한국어
  if (/pdf\s*(로|으로)?\s*(다운로드|받|저장|내려)/i.test(message)) return true;
  if (/(다운로드|저장).{0,8}pdf/i.test(message)) return true;
  // 영어
  if (/download.{0,12}(as|to|in)?\s*pdf/i.test(low)) return true;
  if (/(export|save).{0,12}(as|to|in)?\s*pdf/i.test(low)) return true;
  if (/pdf.{0,10}(download|export|file)/i.test(low)) return true;
  return false;
}

/**
 * 사용자 메시지에서 "PDF로 다운로드" 같은 지시 부분을 제거.
 *
 * AI(특히 GPT-4o-mini)는 "PDF" 단어를 보면 alignment 학습 때문에 "파일 생성
 * 불가" 자동 거부에 빠지는 경향. 메시지를 수정해서 AI에게는 "번역해줘"
 * 같은 순수 task만 전달하고, PDF 변환은 우리 코드가 처리.
 */
export function stripPdfDownloadIntent(message: string): string {
  if (!message) return message;
  let out = message;
  // 한국어 "pdf로 다운로드해줘", "pdf로 받아줘", "pdf로 저장" 등
  out = out.replace(/\s*(?:pdf|PDF)\s*(?:로|으로)?\s*(?:다운로드|받아|받|저장|내려|보내)\s*(?:해|줘|줄래|줄까|할래|돼|드려|받|좀)?\s*[?.!]?\s*/g, ' ');
  // "다운로드 해줘 (pdf)" 같은 변형
  out = out.replace(/\s*(?:다운로드|저장)\s*(?:로|으로|해|줘|줄래|드려)?\s*(?:[(\[]?(?:pdf|PDF)[)\]]?)?\s*/g, ' ');
  // 영어
  out = out.replace(/\s*(?:and\s+)?(?:download|export|save)\s+(?:it\s+)?(?:as|to|in)?\s*(?:pdf|PDF)\s*(?:file)?\s*/gi, ' ');
  out = out.replace(/\s*(?:pdf|PDF)\s*(?:download|export|file)\s*/gi, ' ');
  // 후처리 — 문장 끝 이상한 조사 정리
  out = out.replace(/\s*해\s*서\s*$/g, '해줘');
  out = out.replace(/\s+/g, ' ').trim();
  // 거의 빈 결과면 원본 살려서 (안전장치 — fallback to original)
  if (out.length < 3) return message;
  return out;
}
