// Meeting PDF 출력 — html2pdf.js (Tori P1.3 명세)
// design1 톤 비즈니스 문서 (accent 색 미사용, 흰 배경)

import { sanitizeFilename, formatDateForFilename } from './sanitize-filename';

type MeetingExportData = {
  id: string;
  title: string;
  createdAt: number;
  duration?: string;
  participants?: number;
  summary: string[];
  actionItems: { owner?: string; task: string; dueDate?: string; done?: boolean }[];
  decisions: string[];
  topics: string[];
  fullSummary: string;
  transcript?: { speaker?: string; text: string }[];
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function fmtDateKo(ts: number): string {
  const d = new Date(ts);
  const days = ['일','월','화','수','목','금','토'];
  return `${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일 (${days[d.getDay()]})`;
}

function fmtDateEn(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' });
}

function renderMeetingHTML(meeting: MeetingExportData, lang: 'ko' | 'en'): HTMLElement {
  const isKo = lang === 'ko';
  const labels = {
    summary:    isKo ? '요약' : 'Summary',
    actions:    isKo ? '실행 항목' : 'Action Items',
    decisions:  isKo ? '결정사항' : 'Decisions',
    topics:     isKo ? '토픽' : 'Topics',
    full:       isKo ? '전체 요약' : 'Full Summary',
    transcript: isKo ? '대화 기록' : 'Transcript',
    duration:   isKo ? '분석 시간' : 'Duration',
    participants: isKo ? '참석자' : 'Participants',
    suffix:     isKo ? '명' : '',
    generated:  isKo ? 'Blend로 생성됨' : 'Generated by Blend',
  };
  const dateStr = isKo ? fmtDateKo(meeting.createdAt) : fmtDateEn(meeting.createdAt);

  const div = document.createElement('div');
  div.style.cssText = 'position:absolute;left:-99999px;top:0;';
  div.innerHTML = `
    <div class="d1-meeting-export-doc" style="
      font-family: 'Pretendard Variable', Pretendard, -apple-system, sans-serif;
      color: #0a0a0a; background: #ffffff; padding: 0;
      width: 180mm; line-height: 1.6;
    ">
      <h1 style="font-size:20pt;margin:0 0 8pt 0;font-weight:600;letter-spacing:-0.02em;">
        ${escapeHtml(meeting.title || (isKo ? '회의록' : 'Meeting'))}
      </h1>
      <div style="color:#6b6862;font-size:10pt;line-height:1.5;">
        <div>${dateStr}</div>
        ${meeting.duration ? `<div>${labels.duration}: ${escapeHtml(meeting.duration)}</div>` : ''}
        ${meeting.participants ? `<div>${labels.participants}: ${meeting.participants}${labels.suffix}</div>` : ''}
      </div>
      <hr style="border:none;border-top:1px solid #d4d0c8;margin:12pt 0;" />

      ${meeting.summary.length ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;">${labels.summary}</h2>
        <ul style="padding-left:16pt;line-height:1.6;margin:0;">
          ${meeting.summary.map(s => `<li style="margin:4pt 0;">${escapeHtml(s)}</li>`).join('')}
        </ul>
      ` : ''}

      ${meeting.actionItems.length ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;page-break-after:avoid;">${labels.actions}</h2>
        <ul style="padding-left:16pt;line-height:1.6;list-style:none;margin:0;">
          ${meeting.actionItems.map(item => `
            <li style="margin:4pt 0;page-break-inside:avoid;">
              ${item.done ? '☑' : '☐'}
              ${item.owner ? `<strong>[${escapeHtml(item.owner)}]</strong>` : ''}
              ${escapeHtml(item.task)}
              ${item.dueDate ? `<span style="color:#6b6862;"> · ${escapeHtml(item.dueDate)}</span>` : ''}
            </li>
          `).join('')}
        </ul>
      ` : ''}

      ${meeting.decisions.length ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;">${labels.decisions}</h2>
        <ul style="padding-left:16pt;line-height:1.6;margin:0;">
          ${meeting.decisions.map(d => `<li style="margin:4pt 0;">${escapeHtml(d)}</li>`).join('')}
        </ul>
      ` : ''}

      ${meeting.topics.length ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;">${labels.topics}</h2>
        <p style="line-height:1.6;color:#3a3a3a;">${meeting.topics.map(escapeHtml).join(' · ')}</p>
      ` : ''}

      ${meeting.fullSummary ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;">${labels.full}</h2>
        <p style="line-height:1.7;white-space:pre-wrap;">${escapeHtml(meeting.fullSummary)}</p>
      ` : ''}

      ${meeting.transcript && meeting.transcript.length ? `
        <h2 style="font-size:13pt;margin:16pt 0 6pt 0;font-weight:600;page-break-before:always;">${labels.transcript}</h2>
        <div style="line-height:1.7;">
          ${meeting.transcript.map((seg) => `
            <div style="margin:8pt 0;page-break-inside:avoid;">
              ${seg.speaker ? `<div style="font-size:9pt;font-weight:600;color:#a04000;text-transform:uppercase;letter-spacing:0.04em;margin-bottom:2pt;">${escapeHtml(seg.speaker)}</div>` : ''}
              <p style="margin:0;white-space:pre-wrap;">${escapeHtml(seg.text)}</p>
            </div>
          `).join('')}
        </div>
      ` : ''}

      <div style="margin-top:24pt;padding-top:8pt;border-top:1px solid #e6e2dc;font-size:9pt;color:#a8a49b;text-align:center;font-style:italic;">
        ${labels.generated} · ${dateStr}
      </div>
    </div>
  `;
  return div;
}

export async function exportMeetingPDF(meeting: MeetingExportData, lang: 'ko' | 'en'): Promise<void> {
  // html2pdf.js는 client-only — 동적 import (SSR/정적 빌드 호환)
  const html2pdfModule = (await import('html2pdf.js')).default as (...args: unknown[]) => {
    set: (opts: object) => { from: (el: HTMLElement) => { save: () => Promise<void> } };
  };

  const element = renderMeetingHTML(meeting, lang);
  document.body.appendChild(element);

  const filename = sanitizeFilename(`${meeting.title || 'meeting'}_${formatDateForFilename(meeting.createdAt)}.pdf`);

  const opt = {
    margin: [15, 15, 15, 15],
    filename,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff' },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] as const },
  };

  try {
    await html2pdfModule().set(opt).from(element).save();
  } catch (e) {
    const err = e as Error;
    const wrapped = new Error(err.message || 'PDF export failed') as Error & { code?: string };
    wrapped.code = 'PDF_EXPORT_FAILED';
    throw wrapped;
  } finally {
    if (element.parentNode) element.parentNode.removeChild(element);
  }
}
