// Meeting Word(.docx) 출력 — docx + file-saver (Tori P1.3 명세)

import { sanitizeFilename, formatDateForFilename } from './sanitize-filename';

type MeetingExportData = {
  id: string;
  title: string;
  createdAt: number;
  duration?: string;
  participants?: number;
  summary: string[];
  actionItems: { owner?: string; task: string; dueDate?: string; done?: boolean }[];
  decisions: string[];
  topics: string[];
  fullSummary: string;
  transcript?: { speaker?: string; text: string }[];
};

function fmtDateKo(ts: number): string {
  const d = new Date(ts);
  const days = ['일','월','화','수','목','금','토'];
  return `${d.getFullYear()}년 ${d.getMonth()+1}월 ${d.getDate()}일 (${days[d.getDay()]})`;
}
function fmtDateEn(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' });
}

export async function exportMeetingDocx(meeting: MeetingExportData, lang: 'ko' | 'en'): Promise<void> {
  // 동적 import — 정적 빌드 + 번들 크기 절약
  const docxMod = await import('docx');
  const fileSaverMod = await import('file-saver');
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = docxMod;
  const { saveAs } = fileSaverMod;

  const isKo = lang === 'ko';
  const labels = {
    summary:    isKo ? '요약' : 'Summary',
    actions:    isKo ? '실행 항목' : 'Action Items',
    decisions:  isKo ? '결정사항' : 'Decisions',
    topics:     isKo ? '토픽' : 'Topics',
    full:       isKo ? '전체 요약' : 'Full Summary',
    transcript: isKo ? '대화 기록' : 'Transcript',
    duration:   isKo ? '분석 시간' : 'Duration',
    participants: isKo ? '참석자' : 'Participants',
    suffix:     isKo ? '명' : '',
    generated:  isKo ? 'Blend로 생성됨' : 'Generated by Blend',
  };
  const dateStr = isKo ? fmtDateKo(meeting.createdAt) : fmtDateEn(meeting.createdAt);

  const children: InstanceType<typeof Paragraph>[] = [];

  // 제목
  children.push(new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text: meeting.title || (isKo ? '회의록' : 'Meeting'), bold: true, size: 40 })],
    spacing: { after: 120 },
  }));

  // 메타
  children.push(new Paragraph({
    children: [new TextRun({ text: dateStr, color: '6B6862', size: 20 })],
    spacing: { after: 60 },
  }));
  if (meeting.duration) {
    children.push(new Paragraph({
      children: [new TextRun({ text: `${labels.duration}: ${meeting.duration}`, color: '6B6862', size: 20 })],
      spacing: { after: 60 },
    }));
  }
  if (meeting.participants) {
    children.push(new Paragraph({
      children: [new TextRun({ text: `${labels.participants}: ${meeting.participants}${labels.suffix}`, color: '6B6862', size: 20 })],
      spacing: { after: 240 },
    }));
  }

  // 구분선
  children.push(new Paragraph({
    border: { bottom: { color: 'D4D0C8', size: 6, style: BorderStyle.SINGLE, space: 1 } },
    spacing: { after: 240 },
  }));

  // 요약
  if (meeting.summary.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.summary, bold: true, size: 28 })],
      spacing: { before: 240, after: 120 },
    }));
    meeting.summary.forEach((p) => {
      children.push(new Paragraph({
        bullet: { level: 0 },
        children: [new TextRun({ text: p, size: 22 })],
        spacing: { after: 60 },
      }));
    });
  }

  // 실행 항목
  if (meeting.actionItems.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.actions, bold: true, size: 28 })],
      spacing: { before: 240, after: 120 },
    }));
    meeting.actionItems.forEach((item) => {
      const runs: InstanceType<typeof TextRun>[] = [];
      runs.push(new TextRun({ text: item.done ? '☑ ' : '☐ ', size: 22 }));
      if (item.owner) runs.push(new TextRun({ text: `[${item.owner}] `, bold: true, size: 22 }));
      runs.push(new TextRun({ text: item.task, size: 22 }));
      if (item.dueDate) runs.push(new TextRun({ text: ` · ${item.dueDate}`, color: '6B6862', size: 20 }));
      children.push(new Paragraph({ children: runs, spacing: { after: 80 } }));
    });
  }

  // 결정사항
  if (meeting.decisions.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.decisions, bold: true, size: 28 })],
      spacing: { before: 240, after: 120 },
    }));
    meeting.decisions.forEach((d) => {
      children.push(new Paragraph({
        bullet: { level: 0 },
        children: [new TextRun({ text: d, size: 22 })],
        spacing: { after: 60 },
      }));
    });
  }

  // 토픽
  if (meeting.topics.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.topics, bold: true, size: 28 })],
      spacing: { before: 240, after: 120 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: meeting.topics.join(' · '), size: 22 })],
      spacing: { after: 120 },
    }));
  }

  // 전체 요약
  if (meeting.fullSummary) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.full, bold: true, size: 28 })],
      spacing: { before: 240, after: 120 },
    }));
    meeting.fullSummary.split(/\n\n+/).forEach((para) => {
      children.push(new Paragraph({
        children: [new TextRun({ text: para.replace(/\n/g, ' '), size: 22 })],
        spacing: { after: 120 },
      }));
    });
  }

  // 대화 기록 (원본 transcript)
  if (meeting.transcript && meeting.transcript.length) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [new TextRun({ text: labels.transcript, bold: true, size: 28 })],
      spacing: { before: 360, after: 120 },
      pageBreakBefore: true,
    }));
    meeting.transcript.forEach((seg) => {
      if (seg.speaker) {
        children.push(new Paragraph({
          children: [new TextRun({ text: seg.speaker, bold: true, color: 'A04000', size: 20 })],
          spacing: { before: 120, after: 40 },
        }));
      }
      children.push(new Paragraph({
        children: [new TextRun({ text: seg.text, size: 22 })],
        spacing: { after: 80 },
      }));
    });
  }

  // 푸터
  children.push(new Paragraph({
    border: { top: { color: 'E6E2DC', size: 4, style: BorderStyle.SINGLE, space: 1 } },
    spacing: { before: 480, after: 60 },
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: `${labels.generated} · ${dateStr}`, color: 'A8A49B', size: 18, italics: true })],
  }));

  const doc = new Document({
    creator: 'Blend',
    title: meeting.title || 'Meeting',
    description: 'Meeting notes generated by Blend',
    styles: {
      default: {
        document: { run: { font: 'Pretendard', size: 22 } },
      },
    },
    sections: [{ children }],
  });

  try {
    const blob = await Packer.toBlob(doc);
    const filename = sanitizeFilename(`${meeting.title || 'meeting'}_${formatDateForFilename(meeting.createdAt)}.docx`);
    saveAs(blob, filename);
  } catch (e) {
    const err = e as Error;
    const wrapped = new Error(err.message || 'DOCX export failed') as Error & { code?: string };
    wrapped.code = 'DOCX_EXPORT_FAILED';
    throw wrapped;
  }
}
