// Blend - Model Registry Module (Reusable: any multi-LLM project)
// Defines all supported AI models with pricing and capabilities

import { AIModel } from '@/types';

export const DEFAULT_MODELS: AIModel[] = [
  // ── OpenAI ─────────────────────────────────────────────────────────────────
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    contextLength: 1047576,
    inputPrice: 2,
    outputPrice: 8,
    features: ['vision', 'streaming', 'function_calling'],
    description: '코딩·분석 최강 — 가장 최신 GPT-4',
    enabled: true,
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    provider: 'openai',
    contextLength: 1047576,
    inputPrice: 0.4,
    outputPrice: 1.6,
    features: ['vision', 'streaming', 'function_calling'],
    description: 'GPT-4.1 경량 — 빠르고 저렴',
    enabled: true,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2.5,
    outputPrice: 10,
    features: ['vision', 'streaming', 'function_calling'],
    description: '글·이미지 모두 잘 이해하는 AI',
    enabled: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['vision', 'streaming', 'function_calling'],
    description: '가볍고 빠른 일상 대화용',
    enabled: true,
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'openai',
    contextLength: 200000,
    inputPrice: 10,
    outputPrice: 40,
    features: ['streaming', 'thinking'],
    description: '수학·논리 최고 수준 추론',
    enabled: true,
  },
  {
    id: 'o4-mini',
    name: 'o4-mini',
    provider: 'openai',
    contextLength: 200000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    features: ['vision', 'streaming', 'thinking'],
    description: '추론 특화 — o3보다 빠르고 저렴',
    enabled: true,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'openai',
    contextLength: 16385,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'function_calling'],
    description: '초저가 — 단순 질문·번역용',
    enabled: false,
  },
  {
    id: 'gpt-4-0613',
    name: 'GPT 4',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-4 첫 출시 고정 버전 (2023.06)',
    enabled: false,
  },
  {
    id: 'gpt-4',
    name: 'GPT 4',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '강력한 GPT-4 기본형',
    enabled: false,
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT 5.4 Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 경량판 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-5.4',
    name: 'GPT 5.4',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 — 더 빠르고 정확해진 최신 AI',
    enabled: false,
  },
  {
    id: 'gpt-5.4-nano-2026-03-17',
    name: 'GPT 5.4 Nano 2026 03 17',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '번개같이 빠른 초소형 AI',
    enabled: false,
  },
  {
    id: 'gpt-5.4-nano',
    name: 'GPT 5.4 Nano',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 초소형 — 가장 작고 빠름',
    enabled: false,
  },
  {
    id: 'gpt-5.4-mini-2026-03-17',
    name: 'GPT 5.4 Mini 2026 03 17',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '빠르고 똑똑한 작은 AI',
    enabled: false,
  },
  {
    id: 'gpt-3.5-turbo-instruct',
    name: 'GPT 3.5 Turbo Instruct',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '명령을 잘 따르는 구형 GPT-3.5',
    enabled: false,
  },
  {
    id: 'gpt-3.5-turbo-instruct-0914',
    name: 'GPT 3.5 Turbo Instruct',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-3.5 Instruct 고정 버전 (2023.09)',
    enabled: false,
  },
  {
    id: 'gpt-3.5-turbo-1106',
    name: 'GPT 3.5 Turbo',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-3.5 Turbo 고정 버전 (2023.11)',
    enabled: false,
  },
  {
    id: 'gpt-3.5-turbo-0125',
    name: 'GPT 3.5 Turbo',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-3.5 Turbo 고정 버전 (2024.01)',
    enabled: false,
  },
  {
    id: 'gpt-4-turbo',
    name: 'GPT 4 Turbo',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '빠른 GPT-4 터보 기본형',
    enabled: false,
  },
  {
    id: 'gpt-4-turbo-2024-04-09',
    name: 'GPT 4 Turbo 2024 04 09',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '강력한 GPT-4 계열 AI',
    enabled: false,
  },
  {
    id: 'gpt-4o-2024-05-13',
    name: 'GPT 4o 2024 05 13',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '강력한 GPT-4 계열 AI',
    enabled: false,
  },
  {
    id: 'gpt-4o-mini-2024-07-18',
    name: 'GPT 4o Mini 2024 07 18',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['streaming', 'vision', 'function_calling'],
    description: '가볍고 빠른 일상 대화용',
    enabled: false,
  },
  {
    id: 'gpt-4o-2024-08-06',
    name: 'GPT 4o 2024 08 06',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '가볍고 빠른 일상 대화 AI',
    enabled: false,
  },
  {
    id: 'o1-2024-12-17',
    name: 'O1 2024 12 17',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 60,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '깊게 생각해서 답하는 AI',
    enabled: false,
  },
  {
    id: 'o1',
    name: 'O1',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 60,
    features: ['streaming', 'thinking', 'function_calling'],
    description: '깊게 생각해서 정확하게 답하는 AI',
    enabled: false,
  },
  {
    id: 'o3-mini',
    name: 'O3 Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '어려운 문제를 빠르게 푸는 추론 AI',
    enabled: true,
  },
  {
    id: 'o3-mini-2025-01-31',
    name: 'O3 Mini 2025 01 31',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '추론 특화 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-4o-2024-11-20',
    name: 'GPT 4o 2024 11 20',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '어려운 문제를 빠르게 푸는 작은 AI',
    enabled: false,
  },
  {
    id: 'o1-pro-2025-03-19',
    name: 'O1 Pro 2025 03 19',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 60,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '크고 강력한 고성능 AI',
    enabled: false,
  },
  {
    id: 'o1-pro',
    name: 'O1 Pro',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 60,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: 'o1 최고급 — 가장 어려운 문제용',
    enabled: false,
  },
  {
    id: 'o3-2025-04-16',
    name: 'O3 2025 04 16',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 10,
    outputPrice: 40,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '수학·논리 최고 수준 추론',
    enabled: false,
  },
  {
    id: 'o4-mini-2025-04-16',
    name: 'O4 Mini 2025 04 16',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 1.1,
    outputPrice: 4.4,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '추론 특화 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-4.1-2025-04-14',
    name: 'GPT 4.1 2025 04 14',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '코딩·분석을 제일 잘하는 AI',
    enabled: false,
  },
  {
    id: 'gpt-4.1-mini-2025-04-14',
    name: 'GPT 4.1 Mini 2025 04 14',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-4.1 경량 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-4.1-nano-2025-04-14',
    name: 'GPT 4.1 Nano 2025 04 14',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: '빠르고 저렴한 GPT-4.1 축소판',
    enabled: false,
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT 4.1 Nano',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 2,
    outputPrice: 8,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-4.1 초소형 — 가장 작고 빠름',
    enabled: true,
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    provider: 'openai',
    contextLength: 0,
    inputPrice: 0.04,
    outputPrice: 0,
    features: ['vision'],
    description: '텍스트로 고품질 이미지를 만들어요 — /image 없이 바로 입력',
    enabled: false,
  },
  {
    id: 'gpt-image-1',
    name: 'GPT Image 1',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '텍스트로 그림을 그려주는 AI',
    enabled: false,
  },
  {
    id: 'gpt-5-chat-latest',
    name: 'GPT 5 Chat Latest',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '항상 최신 GPT-5로 자동 연결',
    enabled: false,
  },
  {
    id: 'gpt-5-2025-08-07',
    name: 'GPT 5 2025 08 07',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 기본형 — 글·코딩 모두 능숙',
    enabled: false,
  },
  {
    id: 'gpt-5',
    name: 'GPT 5',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 기본형 — 글·코딩 모두 능숙',
    enabled: false,
  },
  {
    id: 'gpt-5-mini-2025-08-07',
    name: 'GPT 5 Mini 2025 08 07',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '빠르고 똑똑한 작은 AI',
    enabled: false,
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT 5 Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 경량판 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-5-nano-2025-08-07',
    name: 'GPT 5 Nano 2025 08 07',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '번개같이 빠른 초소형 AI',
    enabled: false,
  },
  {
    id: 'gpt-5-nano',
    name: 'GPT 5 Nano',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 초소형 — 번개처럼 빠름',
    enabled: false,
  },
  {
    id: 'gpt-5-codex',
    name: 'GPT 5 Codex',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '코딩 전용으로 특화된 GPT-5',
    enabled: false,
  },
  {
    id: 'gpt-image-1-mini',
    name: 'GPT Image 1 Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '빠르고 저렴한 이미지 생성 AI',
    enabled: false,
  },
  {
    id: 'gpt-5-pro-2025-10-06',
    name: 'GPT 5 Pro 2025 10 06',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 최고급 — 가장 강력',
    enabled: false,
  },
  {
    id: 'gpt-5-pro',
    name: 'GPT 5 Pro',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5 최고급 — 가장 강력한 GPT-5',
    enabled: false,
  },
  {
    id: 'gpt-5.1-chat-latest',
    name: 'GPT 5.1 Chat Latest',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '항상 최신 GPT-5.1로 자동 연결',
    enabled: false,
  },
  {
    id: 'gpt-5.1-2025-11-13',
    name: 'GPT 5.1 2025 11 13',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.1 기본형 — 글·코딩 모두 능숙',
    enabled: false,
  },
  {
    id: 'gpt-5.1',
    name: 'GPT 5.1',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.1 — GPT-5보다 더 빠르고 정확',
    enabled: false,
  },
  {
    id: 'gpt-5.1-codex',
    name: 'GPT 5.1 Codex',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.1 코딩 전문 버전',
    enabled: false,
  },
  {
    id: 'gpt-5.1-codex-mini',
    name: 'GPT 5.1 Codex Mini',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.1 코딩 경량판 — 빠르고 저렴',
    enabled: false,
  },
  {
    id: 'gpt-5.1-codex-max',
    name: 'GPT 5.1 Codex Max',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '어려운 코딩도 거뜬한 GPT-5.1 최강판',
    enabled: false,
  },
  {
    id: 'gpt-image-1.5',
    name: 'GPT Image 1.5',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '더 선명하게 그림 그리는 AI',
    enabled: false,
  },
  {
    id: 'gpt-5.2-2025-12-11',
    name: 'GPT 5.2 2025 12 11',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.2 기본형 — 글·코딩 모두 능숙',
    enabled: false,
  },
  {
    id: 'gpt-5.2',
    name: 'GPT 5.2',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.2 — 더 스마트해진 GPT-5',
    enabled: false,
  },
  {
    id: 'gpt-5.2-pro-2025-12-11',
    name: 'GPT 5.2 Pro 2025 12 11',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.2 최고급 — 가장 강력',
    enabled: false,
  },
  {
    id: 'gpt-5.2-pro',
    name: 'GPT 5.2 Pro',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.2 프로 — 가장 강력한 GPT-5.2',
    enabled: false,
  },
  {
    id: 'gpt-5.2-chat-latest',
    name: 'GPT 5.2 Chat Latest',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '항상 최신 GPT-5.2로 자동 연결',
    enabled: false,
  },
  {
    id: 'gpt-5.2-codex',
    name: 'GPT 5.2 Codex',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.2 코딩 전문 버전',
    enabled: false,
  },
  {
    id: 'gpt-5.3-codex',
    name: 'GPT 5.3 Codex',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.3 코딩 전문 버전',
    enabled: false,
  },
  {
    id: 'gpt-5.3-chat-latest',
    name: 'GPT 5.3 Chat Latest',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '항상 최신 GPT-5.3으로 자동 연결',
    enabled: false,
  },
  {
    id: 'gpt-5.4-2026-03-05',
    name: 'GPT 5.4 2026 03 05',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 기본형 — 글·코딩 모두 능숙',
    enabled: false,
  },
  {
    id: 'gpt-5.4-pro',
    name: 'GPT 5.4 Pro',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 최고급 — 가장 강력한 GPT-5.4',
    enabled: false,
  },
  {
    id: 'gpt-5.4-pro-2026-03-05',
    name: 'GPT 5.4 Pro 2026 03 05',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: 'GPT-5.4 최고급 — 가장 강력',
    enabled: false,
  },
  {
    id: 'gpt-3.5-turbo-16k',
    name: 'GPT 3.5 Turbo 16k',
    provider: 'openai',
    contextLength: 128000,
    inputPrice: 0.5,
    outputPrice: 1.5,
    features: ['streaming', 'vision', 'function_calling'],
    description: '긴 문서도 처리하는 구형 GPT-3.5',
    enabled: false,
  },
  // ── Anthropic ──────────────────────────────────────────────────────────────
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic',
    contextLength: 200000,
    inputPrice: 15,
    outputPrice: 75,
    features: ['vision', 'streaming', 'thinking'],
    description: '최신 Claude Opus — 가장 강력',
    enabled: true,
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    contextLength: 200000,
    inputPrice: 3,
    outputPrice: 15,
    features: ['vision', 'streaming', 'thinking'],
    description: '최신 Claude Sonnet — 빠르고 정확',
    enabled: true,
  },
  {
    id: 'claude-haiku-4-5-20251001',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    contextLength: 200000,
    inputPrice: 0.8,
    outputPrice: 4,
    features: ['vision', 'streaming'],
    description: '빠른 Claude Haiku 고정 버전',
    enabled: false,
  },
  {
    id: 'claude-3-5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    contextLength: 200000,
    inputPrice: 3,
    outputPrice: 15,
    features: ['vision', 'streaming'],
    description: '이전 세대 Sonnet — 안정적',
    enabled: false,
  },
  {
    id: 'claude-3-haiku-20240307',
    name: 'Claude 3 Haiku',
    provider: 'anthropic',
    contextLength: 200000,
    inputPrice: 0.25,
    outputPrice: 1.25,
    features: ['vision', 'streaming'],
    description: '초저가 — 가장 빠른 Claude',
    enabled: false,
  },
  {
    id: 'claude-opus-4-5-20251101',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 75,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '긴 문서·복잡 분석 최강',
    enabled: false,
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    contextLength: 128000,
    inputPrice: 3,
    outputPrice: 15,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '코딩 잘하는 AI — 균형 최고',
    enabled: false,
  },
  {
    id: 'claude-opus-4-1-20250805',
    name: 'Claude Opus 4.1',
    provider: 'anthropic',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 75,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '긴 문서·복잡 분석 최강',
    enabled: false,
  },
  {
    id: 'claude-opus-4-20250514',
    name: 'Claude Opus 4',
    provider: 'anthropic',
    contextLength: 128000,
    inputPrice: 15,
    outputPrice: 75,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '긴 문서·복잡 분석 최강',
    enabled: false,
  },
  {
    id: 'claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    contextLength: 128000,
    inputPrice: 3,
    outputPrice: 15,
    features: ['streaming', 'vision', 'thinking', 'function_calling'],
    description: '코딩 잘하는 AI — 균형 최고',
    enabled: false,
  },
  // ── Google ─────────────────────────────────────────────────────────────────
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 1.25,
    outputPrice: 10,
    features: ['vision', 'streaming', 'thinking'],
    description: '책 한 권도 한 번에 읽는 구글 최강 AI',
    enabled: true,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['vision', 'streaming', 'thinking'],
    description: '빠르고 저렴한 구글 최신 AI',
    enabled: true,
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    features: ['vision', 'streaming'],
    description: '구글에서 가장 저렴한 AI',
    enabled: false, // deprecated — "no longer available to new users"
  },
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    contextLength: 2000000,
    inputPrice: 1.25,
    outputPrice: 5,
    features: ['vision', 'streaming'],
    description: '200만 글자도 한 번에 읽는 AI',
    enabled: false,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    features: ['vision', 'streaming'],
    description: '빠른 구글 1.5 AI',
    enabled: false,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '빠른 구글 AI — 일상 작업용',
    enabled: true,
  },
  {
    id: 'gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash 001',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '빠른 구글 AI — 일상 작업용',
    enabled: false,
  },
  {
    id: 'gemini-2.0-flash-lite-001',
    name: 'Gemini 2.0 Flash-Lite 001',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.075,
    outputPrice: 0.3,
    features: ['streaming', 'vision'],
    description: '구글 가장 저렴 — 일상 작업',
    enabled: false,
  },
  {
    id: 'gemini-2.5-flash-preview-tts',
    name: 'Gemini 2.5 Flash Preview TTS',
    provider: 'google',
    contextLength: 8192,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['streaming', 'vision', 'thinking'],
    description: '빠르고 저렴한 Gemini 최신형',
    enabled: false,
  },
  {
    id: 'gemini-2.5-pro-preview-tts',
    name: 'Gemini 2.5 Pro Preview TTS',
    provider: 'google',
    contextLength: 8192,
    inputPrice: 1.25,
    outputPrice: 10,
    features: ['streaming', 'vision', 'thinking'],
    description: '100만 토큰 — 초대형 문서 분석',
    enabled: false,
  },
  {
    id: 'gemma-3-1b-it',
    name: 'Gemma 3 1B',
    provider: 'google',
    contextLength: 32768,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글에서 가장 저렴한 AI',
    enabled: false,
  },
  {
    id: 'gemma-3-4b-it',
    name: 'Gemma 3 4B',
    provider: 'google',
    contextLength: 32768,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글이 만든 초소형 AI — 4B 매개변수',
    enabled: false,
  },
  {
    id: 'gemma-3-12b-it',
    name: 'Gemma 3 12B',
    provider: 'google',
    contextLength: 32768,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글이 만든 중형 오픈 AI',
    enabled: false,
  },
  {
    id: 'gemma-3-27b-it',
    name: 'Gemma 3 27B',
    provider: 'google',
    contextLength: 131072,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글이 만든 대형 오픈 AI',
    enabled: false,
  },
  {
    id: 'gemma-3n-e4b-it',
    name: 'Gemma 3n E4B',
    provider: 'google',
    contextLength: 8192,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 Gemma 3n 경량 AI',
    enabled: false,
  },
  {
    id: 'gemma-3n-e2b-it',
    name: 'Gemma 3n E2B',
    provider: 'google',
    contextLength: 8192,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 Gemma 3n 초소형 AI',
    enabled: false,
  },
  {
    id: 'gemma-4-26b-a4b-it',
    name: 'Gemma 4 26B A4B IT',
    provider: 'google',
    contextLength: 262144,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 최신 Gemma 4세대 AI',
    enabled: false,
  },
  {
    id: 'gemma-4-31b-it',
    name: 'Gemma 4 31B IT',
    provider: 'google',
    contextLength: 262144,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 Gemma 4 대형 AI',
    enabled: false,
  },
  {
    id: 'gemini-flash-latest',
    name: 'Gemini Flash Latest',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '번개처럼 빠른 구글 AI',
    enabled: false,
  },
  {
    id: 'gemini-flash-lite-latest',
    name: 'Gemini Flash-Lite Latest',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '번개처럼 빠른 구글 AI',
    enabled: false,
  },
  {
    id: 'gemini-pro-latest',
    name: 'Gemini Pro Latest',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '전문가 수준의 구글 AI',
    enabled: false,
  },
  {
    id: 'gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['streaming', 'vision', 'thinking'],
    description: '빠르고 저렴한 Gemini 최신형',
    enabled: true,
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'Gemini 2.5 Flash Image',
    provider: 'google',
    contextLength: 32768,
    inputPrice: 0.15,
    outputPrice: 0.6,
    features: ['streaming', 'vision', 'thinking'],
    description: 'Gemini 2.5 Flash 이미지 생성 특화 모델',
    enabled: true,
  },
  {
    id: 'gemini-3-pro-preview',
    name: 'Gemini 3 Pro Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '빠르고 저렴한 구글 최신 AI',
    enabled: false,
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 3세대 빠른 AI',
    enabled: false,
  },
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '전문가 수준의 구글 AI',
    enabled: false,
  },
  {
    id: 'gemini-3.1-pro-preview-customtools',
    name: 'Gemini 3.1 Pro Preview Custom Tools',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '전문가 수준의 구글 AI',
    enabled: false,
  },
  {
    id: 'gemini-3.1-flash-lite-preview',
    name: 'Gemini 3.1 Flash Lite Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 3세대 빠른 AI',
    enabled: false,
  },
  {
    id: 'gemini-3-pro-image-preview',
    name: 'Gemini 3 Pro Image Preview',
    provider: 'google',
    contextLength: 131072,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 최신 프로급 AI',
    enabled: false,
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    name: 'Gemini 3.1 Flash Image Preview',
    provider: 'google',
    contextLength: 65536,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 3세대 빠른 AI',
    enabled: false,
  },
  {
    id: 'lyria-3-clip-preview',
    name: 'Lyria 3 Clip Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 음악·멀티미디어 AI',
    enabled: false,
  },
  {
    id: 'lyria-3-pro-preview',
    name: 'Lyria 3 Pro Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '구글 최신 프로급 AI',
    enabled: false,
  },
  {
    id: 'gemini-robotics-er-1.5-preview',
    name: 'Gemini Robotics-ER 1.5 Preview',
    provider: 'google',
    contextLength: 1048576,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '로봇·자동화 전문 AI',
    enabled: false,
  },
  {
    id: 'gemini-2.5-computer-use-preview-10-2025',
    name: 'Gemini 2.5 Computer Use Preview 10-2025',
    provider: 'google',
    contextLength: 131072,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision', 'thinking'],
    description: '컴퓨터를 직접 조작하는 AI',
    enabled: false,
  },
  {
    id: 'deep-research-pro-preview-12-2025',
    name: 'Deep Research Pro Preview (Dec-12-2025)',
    provider: 'google',
    contextLength: 131072,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '전문가 수준의 구글 AI',
    enabled: false,
  },

  // ── DeepSeek ───────────────────────────────────────────────────────────────
  {
    id: 'deepseek-chat',
    name: 'DeepSeek-V3',
    provider: 'deepseek',
    contextLength: 64000,
    inputPrice: 0.27,
    outputPrice: 1.1,
    features: ['streaming', 'function_calling'],
    description: '중국발 최강 코딩·추론 — GPT-4급을 1/10 가격에',
    enabled: false,
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek-R1',
    provider: 'deepseek',
    contextLength: 64000,
    inputPrice: 0.55,
    outputPrice: 2.19,
    features: ['streaming', 'thinking'],
    description: 'o1급 추론 모델 — 수학·논리·코드 특화',
    enabled: false,
  },

  // ── Groq ──────────────────────────────────────────────────────────────────
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B',
    provider: 'groq',
    contextLength: 128000,
    inputPrice: 0.59,
    outputPrice: 0.79,
    features: ['streaming', 'function_calling'],
    description: 'Meta 최신 70B — 빠르고 균형 잡힌 성능',
    enabled: false,
  },
  {
    id: 'llama-3.1-8b-instant',
    name: 'Llama 3.1 8B',
    provider: 'groq',
    contextLength: 128000,
    inputPrice: 0.05,
    outputPrice: 0.08,
    features: ['streaming', 'function_calling'],
    description: '초고속 초저가 — 간단 질의응답용',
    enabled: false,
  },
  {
    id: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B',
    provider: 'groq',
    contextLength: 32768,
    inputPrice: 0.24,
    outputPrice: 0.24,
    features: ['streaming', 'function_calling'],
    description: 'MoE 구조 — 다국어·코드 균형',
    enabled: false, // decommissioned by Groq
  },
  {
    id: 'gemma2-9b-it',
    name: 'Gemma 2 9B',
    provider: 'groq',
    contextLength: 8192,
    inputPrice: 0.2,
    outputPrice: 0.2,
    features: ['streaming'],
    description: 'Google 경량 오픈모델 — 일상 대화용',
    enabled: false,
  },
  {
    id: 'nano-banana-pro-preview',
    name: 'Nano Banana Pro',
    provider: 'google',
    contextLength: 131072,
    inputPrice: 0.1,
    outputPrice: 0.4,
    features: ['streaming', 'vision'],
    description: '전문가 수준의 구글 AI',
    enabled: false,
  },
];

export function getModelById(id: string, customModels: AIModel[] = []): AIModel | undefined {
  return [...DEFAULT_MODELS, ...customModels].find((m) => m.id === id);
}

export function getModelsByProvider(provider: string): AIModel[] {
  return DEFAULT_MODELS.filter((m) => m.provider === provider);
}

export function calculateCost(model: AIModel, inputTokens: number, outputTokens: number): number {
  return (inputTokens * model.inputPrice + outputTokens * model.outputPrice) / 1_000_000;
}

export function getProviderColor(provider: string): string {
  const colors: Record<string, string> = {
    openai: '#10a37f',
    anthropic: '#d4a574',
    google: '#4285f4',
    deepseek: '#4D6BFE',
    groq: '#F55036',
    custom: '#6b7280',
  };
  return colors[provider] || colors.custom;
}

export type ModelCategory = 'flagship' | 'fast' | 'reasoning' | 'image';

export function getModelCategory(model: AIModel): ModelCategory {
  const lc = model.id.toLowerCase();
  if (/image/.test(lc)) return 'image';
  if (model.features.includes('thinking') || /^o[134]|reasoner|r1(-|$)/.test(lc)) return 'reasoning';
  if (/mini|nano|lite|haiku|flash|turbo|instant|8b|4b|2b|small/.test(lc)) return 'fast';
  return 'flagship';
}

export const MODEL_CATEGORY_META: Record<ModelCategory, { emoji: string; label: string; order: number }> = {
  flagship:  { emoji: '💪', label: '강력',       order: 1 },
  fast:      { emoji: '🚀', label: '빠르고 저렴', order: 2 },
  reasoning: { emoji: '🧠', label: '추론 특화',   order: 3 },
  image:     { emoji: '🎨', label: '이미지 생성', order: 4 },
};

export const PROVIDER_META: Record<string, { label: string; color: string }> = {
  openai:    { label: 'OpenAI',    color: '#10a37f' },
  anthropic: { label: 'Anthropic', color: '#d4a574' },
  google:    { label: 'Google',    color: '#4285f4' },
  deepseek:  { label: 'DeepSeek',  color: '#4D6BFE' },
  groq:      { label: 'Groq',      color: '#F55036' },
  custom:    { label: 'Custom',    color: '#6b7280' },
};
