'use client';

// Google Drive 폴더 선택 모달 — Drive API v3 기반 자체 picker UI.
// Google Picker SDK(popup)는 모바일 불안정 + 자동 생성 hex 폴더 필터링 X.
// OneDriveFolderModal과 동일한 패턴.

import { useEffect, useMemo, useState } from 'react';
import { makeSelection } from '@/modules/datasources/pickers/picker-shared';
import type { DataSourceSelection } from '@/types';

interface DriveFolder {
  id: string;
  name: string;
}

interface Props {
  open: boolean;
  accessToken: string | null;
  lang: 'ko' | 'en';
  onPicked: (selections: DataSourceSelection[]) => void;
  onCancel: () => void;
}

const t = {
  ko: {
    title: 'Google Drive 폴더 선택',
    desc: 'AI가 참고할 폴더를 골라주세요. 여러 개 선택할 수 있어요.',
    loading: '폴더를 불러오고 있어요…',
    empty: 'Google Drive에 폴더가 없어요. 먼저 폴더를 만들어주세요.',
    error: '폴더를 불러오지 못했어요. 잠시 후 다시 시도해주세요.',
    cancel: '취소',
    done: '선택 완료',
    selected: (n: number) => `${n}개 선택`,
    hiddenShow: (n: number) => `숨겨진 ${n}개 폴더 보기 (앱 자동 생성)`,
    hiddenHide: '자동 생성 폴더 다시 숨기기',
  },
  en: {
    title: 'Choose Google Drive folders',
    desc: 'Pick folders for AI to reference. You can select multiple.',
    loading: 'Loading folders…',
    empty: 'No folders found in Google Drive. Create a folder first.',
    error: 'Could not load folders. Please try again in a moment.',
    cancel: 'Cancel',
    done: 'Done',
    selected: (n: number) => `${n} selected`,
    hiddenShow: (n: number) => `Show ${n} hidden folders (auto-generated)`,
    hiddenHide: 'Hide auto-generated folders',
  },
};

// 자동 생성으로 보이는 폴더 패턴: 1~4자리 hex 또는 UUID 형태.
// "a8", "f9", "4c" 등 백업/캐시 도구가 만드는 hash prefix 폴더 매칭.
const AUTO_PATTERN = /^([0-9a-fA-F]{1,4}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;

function isAutoGenerated(name: string): boolean {
  return AUTO_PATTERN.test(name.trim());
}

export function GoogleDriveFolderModal({ open, accessToken, lang, onPicked, onCancel }: Props) {
  const c = t[lang];
  const [folders, setFolders] = useState<DriveFolder[]>([]);
  const [loading, setLoading] = useState(false);
  const [errored, setErrored] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [showHidden, setShowHidden] = useState(false);
  const [confirming, setConfirming] = useState(false);

  useEffect(() => {
    if (!open || !accessToken) return;
    let cancelled = false;
    setLoading(true);
    setErrored(false);
    setSelectedIds(new Set());
    setShowHidden(false);

    const params = new URLSearchParams({
      q: "mimeType='application/vnd.google-apps.folder' and 'root' in parents and trashed=false",
      pageSize: '200',
      fields: 'files(id,name)',
      orderBy: 'name',
    });

    fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    })
      .then(async (r) => {
        if (!r.ok) throw new Error(`drive ${r.status}`);
        const data = (await r.json()) as { files?: DriveFolder[] };
        if (cancelled) return;
        setFolders(data.files ?? []);
        setLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        setErrored(true);
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [open, accessToken]);

  const { visible, hiddenCount } = useMemo(() => {
    const auto = folders.filter((f) => isAutoGenerated(f.name));
    const real = folders.filter((f) => !isAutoGenerated(f.name));
    return {
      visible: showHidden ? folders : real,
      hiddenCount: auto.length,
    };
  }, [folders, showHidden]);

  if (!open) return null;

  const toggle = (id: string) =>
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const handleDone = async () => {
    const picked = folders.filter((f) => selectedIds.has(f.id));
    setConfirming(true);
    // [2026-05-01 Roy] 각 폴더의 1단계 자식 파일 수 + size 합계를 가져와
    // cost preview를 정확하게. 폴더 자체는 카운트 X.
    const stats = await Promise.all(
      picked.map(async (f) => {
        try {
          const params = new URLSearchParams({
            q: `'${f.id}' in parents and trashed=false`,
            fields: 'files(size,mimeType)',
            pageSize: '1000',
          });
          const r = await fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
            headers: { Authorization: `Bearer ${accessToken}` },
          });
          if (!r.ok) return { fileCount: 0, approxBytes: 0 };
          const data = (await r.json()) as { files?: Array<{ size?: string; mimeType?: string }> };
          const files = (data.files ?? []).filter((x) => x.mimeType !== 'application/vnd.google-apps.folder');
          const approxBytes = files.reduce((sum, x) => sum + (parseInt(x.size ?? '0', 10) || 0), 0);
          return { fileCount: files.length, approxBytes };
        } catch {
          return { fileCount: 0, approxBytes: 0 };
        }
      }),
    );
    const selections = picked.map((f, i) =>
      makeSelection({
        id: f.id,
        kind: 'folder',
        name: f.name,
        path: f.name,
        fileCount: stats[i].fileCount,
        approxBytes: stats[i].approxBytes,
      }),
    );
    setConfirming(false);
    onPicked(selections);
  };

  return (
    <div
      className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-4"
      onClick={onCancel}
    >
      <div
        className="w-full max-w-md rounded-2xl p-6 shadow-2xl"
        style={{ background: 'var(--d1-bg)', color: 'var(--d1-text)' }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-1 flex items-center gap-2 text-[15px] font-semibold">
          <span aria-hidden>📁</span>
          {c.title}
        </div>
        <p className="mb-4 text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
          {c.desc}
        </p>

        <div
          className="max-h-72 overflow-y-auto rounded-xl border"
          style={{ borderColor: 'var(--d1-border)' }}
        >
          {loading && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.loading}
            </div>
          )}
          {!loading && errored && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.error}
            </div>
          )}
          {!loading && !errored && visible.length === 0 && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.empty}
            </div>
          )}
          {!loading && !errored && visible.length > 0 && (
            <ul className="divide-y" style={{ borderColor: 'var(--d1-border)' }}>
              {visible.map((f) => {
                const checked = selectedIds.has(f.id);
                return (
                  <li key={f.id}>
                    <label
                      className="flex cursor-pointer items-center gap-3 px-4 py-3 transition-colors hover:bg-black/5"
                      style={{ borderColor: 'var(--d1-border)' }}
                    >
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() => toggle(f.id)}
                        className="h-4 w-4"
                      />
                      <span aria-hidden>📁</span>
                      <span className="flex-1 truncate text-[14px]">{f.name}</span>
                    </label>
                  </li>
                );
              })}
            </ul>
          )}
        </div>

        {!loading && !errored && hiddenCount > 0 && (
          <button
            type="button"
            onClick={() => setShowHidden((v) => !v)}
            className="mt-2 text-[12px] underline-offset-2 hover:underline"
            style={{ color: 'var(--d1-text-dim)' }}
          >
            {showHidden ? c.hiddenHide : c.hiddenShow(hiddenCount)}
          </button>
        )}

        <div className="mt-5 flex items-center justify-between gap-3">
          <span className="text-[12px]" style={{ color: 'var(--d1-text-dim)' }}>
            {selectedIds.size > 0 ? c.selected(selectedIds.size) : ''}
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={onCancel}
              className="rounded-lg px-4 py-2 text-[13px] transition-colors hover:bg-black/5"
              style={{ color: 'var(--d1-text-dim)' }}
            >
              {c.cancel}
            </button>
            <button
              type="button"
              onClick={handleDone}
              disabled={selectedIds.size === 0 || confirming}
              className="rounded-lg px-4 py-2 text-[13px] font-semibold transition-opacity"
              style={{
                background: 'var(--d1-accent)',
                color: '#fff',
                opacity: selectedIds.size === 0 || confirming ? 0.4 : 1,
                cursor: selectedIds.size === 0 || confirming ? 'not-allowed' : 'pointer',
              }}
            >
              {confirming ? (lang === 'ko' ? '확인 중…' : 'Checking…') : c.done}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
