'use client';

// Google Drive 폴더+파일 선택 모달 — Drive API v3 기반 자체 picker UI.
// Google Picker SDK(popup)는 모바일 불안정 + 자동 생성 hex 폴더 필터링 X.
// OneDriveFolderModal과 동일한 패턴.
//
// [2026-05-01 Roy] 폴더만이 아니라 파일도 선택 가능 — root 1단계의 폴더와
// 지원 확장자 파일을 동시 표시. 사용자 명시 요청.

import { useEffect, useMemo, useState } from 'react';
import {
  ALLOWED_MIME_TYPES,
  isAllowedExtension,
  makeSelection,
} from '@/modules/datasources/pickers/picker-shared';
import type { DataSourceSelection } from '@/types';

interface DriveItem {
  id: string;
  name: string;
  mimeType: string;
  size?: string;
}

interface Props {
  open: boolean;
  accessToken: string | null;
  lang: 'ko' | 'en';
  onPicked: (selections: DataSourceSelection[]) => void;
  onCancel: () => void;
}

const t = {
  ko: {
    title: 'Google Drive 항목 선택',
    desc: 'AI가 참고할 폴더 또는 파일을 골라주세요. 여러 개 선택할 수 있어요.',
    loading: '불러오고 있어요…',
    empty: 'Google Drive에 항목이 없어요. (지원: PDF · DOCX · TXT · MD · CSV · XLSX)',
    error: '항목을 불러오지 못했어요. 잠시 후 다시 시도해주세요.',
    cancel: '취소',
    done: '선택 완료',
    selected: (n: number) => `${n}개 선택`,
    hiddenShow: (n: number) => `숨겨진 ${n}개 폴더 보기 (앱 자동 생성)`,
    hiddenHide: '자동 생성 폴더 다시 숨기기',
    sectionFolders: '폴더',
    sectionFiles: '파일',
  },
  en: {
    title: 'Choose Google Drive items',
    desc: 'Pick folders or files for AI to reference. You can select multiple.',
    loading: 'Loading…',
    empty: 'Nothing found in Google Drive. (Supported: PDF · DOCX · TXT · MD · CSV · XLSX)',
    error: 'Could not load items. Please try again in a moment.',
    cancel: 'Cancel',
    done: 'Done',
    selected: (n: number) => `${n} selected`,
    hiddenShow: (n: number) => `Show ${n} hidden folders (auto-generated)`,
    hiddenHide: 'Hide auto-generated folders',
    sectionFolders: 'Folders',
    sectionFiles: 'Files',
  },
};

const FOLDER_MIME = 'application/vnd.google-apps.folder';

const AUTO_PATTERN = /^([0-9a-fA-F]{1,4}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$/;
function isAutoGenerated(name: string): boolean {
  return AUTO_PATTERN.test(name.trim());
}

function fmtBytes(n?: string | number): string {
  const v = typeof n === 'string' ? parseInt(n, 10) : (n ?? 0);
  if (!v || isNaN(v)) return '';
  if (v < 1024) return `${v} B`;
  if (v < 1024 * 1024) return `${(v / 1024).toFixed(1)} KB`;
  if (v < 1024 * 1024 * 1024) return `${(v / 1024 / 1024).toFixed(1)} MB`;
  return `${(v / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

function extOf(name: string): string {
  return name.split('.').pop()?.toLowerCase() ?? '';
}

export function GoogleDriveFolderModal({ open, accessToken, lang, onPicked, onCancel }: Props) {
  const c = t[lang];
  const [items, setItems] = useState<DriveItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [errored, setErrored] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [showHidden, setShowHidden] = useState(false);
  const [confirming, setConfirming] = useState(false);

  useEffect(() => {
    if (!open || !accessToken) return;
    let cancelled = false;
    setLoading(true);
    setErrored(false);
    setSelectedIds(new Set());
    setShowHidden(false);

    // [2026-05-01 Roy] 폴더 + 지원 mime 모두 쿼리. orderBy='folder,name'으로 폴더 먼저.
    // 일부 Drive 항목은 ext 기반 mime 미지정도 있어 클라이언트 측 ext 필터로 보강.
    const mimeQuery = ALLOWED_MIME_TYPES.map((m) => `mimeType='${m}'`).join(' or ');
    const params = new URLSearchParams({
      q: `'root' in parents and trashed=false and (${mimeQuery})`,
      pageSize: '500',
      fields: 'files(id,name,mimeType,size)',
      orderBy: 'folder,name',
    });

    fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
      headers: { Authorization: `Bearer ${accessToken}` },
    })
      .then(async (r) => {
        if (!r.ok) throw new Error(`drive ${r.status}`);
        const data = (await r.json()) as { files?: DriveItem[] };
        if (cancelled) return;
        // 폴더는 모두 통과, 파일은 ext 화이트리스트만.
        const filtered = (data.files ?? []).filter((f) =>
          f.mimeType === FOLDER_MIME ? true : isAllowedExtension(f.name),
        );
        setItems(filtered);
        setLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        setErrored(true);
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [open, accessToken]);

  const { folders, files, hiddenCount } = useMemo(() => {
    const fld = items.filter((x) => x.mimeType === FOLDER_MIME);
    const fls = items.filter((x) => x.mimeType !== FOLDER_MIME);
    const auto = fld.filter((x) => isAutoGenerated(x.name));
    const real = fld.filter((x) => !isAutoGenerated(x.name));
    return {
      folders: showHidden ? fld : real,
      files: fls,
      hiddenCount: auto.length,
    };
  }, [items, showHidden]);

  if (!open) return null;

  const toggle = (id: string) =>
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  const handleDone = async () => {
    const picked = items.filter((f) => selectedIds.has(f.id));
    if (!accessToken) return;
    setConfirming(true);
    // 폴더는 1단계 children만 fetch해서 fileCount/approxBytes 추정. 파일은 자체 size.
    const stats = await Promise.all(
      picked.map(async (f) => {
        if (f.mimeType !== FOLDER_MIME) {
          return { fileCount: 1, approxBytes: parseInt(f.size ?? '0', 10) || 0 };
        }
        try {
          const params = new URLSearchParams({
            q: `'${f.id}' in parents and trashed=false`,
            fields: 'files(size,mimeType)',
            pageSize: '1000',
          });
          const r = await fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
            headers: { Authorization: `Bearer ${accessToken}` },
          });
          if (!r.ok) return { fileCount: 0, approxBytes: 0 };
          const data = (await r.json()) as { files?: Array<{ size?: string; mimeType?: string }> };
          const childFiles = (data.files ?? []).filter((x) => x.mimeType !== FOLDER_MIME);
          const approxBytes = childFiles.reduce((sum, x) => sum + (parseInt(x.size ?? '0', 10) || 0), 0);
          return { fileCount: childFiles.length, approxBytes };
        } catch {
          return { fileCount: 0, approxBytes: 0 };
        }
      }),
    );
    const selections = picked.map((f, i) =>
      makeSelection({
        id: f.id,
        kind: f.mimeType === FOLDER_MIME ? 'folder' : 'file',
        name: f.name,
        path: f.name,
        fileCount: stats[i].fileCount,
        approxBytes: stats[i].approxBytes,
      }),
    );
    setConfirming(false);
    onPicked(selections);
  };

  const isEmpty = !loading && !errored && folders.length === 0 && files.length === 0;

  return (
    <div
      className="fixed inset-0 z-[60] grid place-items-center bg-black/40 p-4"
      onClick={() => { if (!confirming) onCancel(); }}
    >
      <div
        className="w-full max-w-md rounded-2xl p-6 shadow-2xl"
        style={{ background: 'var(--d1-bg)', color: 'var(--d1-text)' }}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-1 flex items-center gap-2 text-[15px] font-semibold">
          <span aria-hidden>☁️</span>
          {c.title}
        </div>
        <p className="mb-4 text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
          {c.desc}
        </p>

        <div
          className="max-h-72 overflow-y-auto rounded-xl border"
          style={{ borderColor: 'var(--d1-border)' }}
        >
          {loading && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.loading}
            </div>
          )}
          {!loading && errored && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.error}
            </div>
          )}
          {isEmpty && (
            <div className="px-4 py-8 text-center text-[13px]" style={{ color: 'var(--d1-text-dim)' }}>
              {c.empty}
            </div>
          )}
          {!loading && !errored && (folders.length > 0 || files.length > 0) && (
            <div>
              {folders.length > 0 && (
                <>
                  <div
                    className="px-4 py-1.5 text-[11px] font-medium uppercase tracking-[0.05em]"
                    style={{ background: 'var(--d1-surface-alt)', color: 'var(--d1-text-faint)' }}
                  >
                    {c.sectionFolders} · {folders.length}
                  </div>
                  <ul className="divide-y" style={{ borderColor: 'var(--d1-border)' }}>
                    {folders.map((f) => {
                      const checked = selectedIds.has(f.id);
                      return (
                        <li key={f.id}>
                          <label className="flex cursor-pointer items-center gap-3 px-4 py-3 transition-colors hover:bg-black/5">
                            <input
                              type="checkbox"
                              checked={checked}
                              onChange={() => toggle(f.id)}
                              className="h-4 w-4"
                            />
                            <span aria-hidden>📁</span>
                            <span className="flex-1 truncate text-[14px]">{f.name}</span>
                          </label>
                        </li>
                      );
                    })}
                  </ul>
                </>
              )}
              {files.length > 0 && (
                <>
                  <div
                    className="px-4 py-1.5 text-[11px] font-medium uppercase tracking-[0.05em]"
                    style={{ background: 'var(--d1-surface-alt)', color: 'var(--d1-text-faint)' }}
                  >
                    {c.sectionFiles} · {files.length}
                  </div>
                  <ul className="divide-y" style={{ borderColor: 'var(--d1-border)' }}>
                    {files.map((f) => {
                      const checked = selectedIds.has(f.id);
                      const ext = extOf(f.name);
                      return (
                        <li key={f.id}>
                          <label className="flex cursor-pointer items-center gap-3 px-4 py-3 transition-colors hover:bg-black/5">
                            <input
                              type="checkbox"
                              checked={checked}
                              onChange={() => toggle(f.id)}
                              className="h-4 w-4"
                            />
                            <span aria-hidden>📄</span>
                            <span className="flex-1 truncate text-[14px]">{f.name}</span>
                            {ext && (
                              <span
                                className="rounded-md px-1.5 py-0.5 text-[10px] font-medium uppercase"
                                style={{ background: 'var(--d1-accent-soft)', color: 'var(--d1-accent)' }}
                              >
                                {ext}
                              </span>
                            )}
                            {f.size && (
                              <span className="text-[11px] tabular-nums" style={{ color: 'var(--d1-text-faint)' }}>
                                {fmtBytes(f.size)}
                              </span>
                            )}
                          </label>
                        </li>
                      );
                    })}
                  </ul>
                </>
              )}
            </div>
          )}
        </div>

        {!loading && !errored && hiddenCount > 0 && (
          <button
            type="button"
            onClick={() => setShowHidden((v) => !v)}
            className="mt-2 text-[12px] underline-offset-2 hover:underline"
            style={{ color: 'var(--d1-text-dim)' }}
          >
            {showHidden ? c.hiddenHide : c.hiddenShow(hiddenCount)}
          </button>
        )}

        <div className="mt-5 flex items-center justify-between gap-3">
          <span className="text-[12px]" style={{ color: 'var(--d1-text-dim)' }}>
            {selectedIds.size > 0 ? c.selected(selectedIds.size) : ''}
          </span>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={onCancel}
              className="rounded-lg px-4 py-2 text-[13px] transition-colors hover:bg-black/5"
              style={{ color: 'var(--d1-text-dim)' }}
            >
              {c.cancel}
            </button>
            <button
              type="button"
              onClick={handleDone}
              disabled={selectedIds.size === 0 || confirming}
              className="rounded-lg px-4 py-2 text-[13px] font-semibold transition-opacity"
              style={{
                background: 'var(--d1-accent)',
                color: '#fff',
                opacity: selectedIds.size === 0 || confirming ? 0.4 : 1,
                cursor: selectedIds.size === 0 || confirming ? 'not-allowed' : 'pointer',
              }}
            >
              {confirming ? (lang === 'ko' ? '확인 중…' : 'Checking…') : c.done}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
